[versions]
android-plugin = "8.1.0"
kotlin = "1.9.0"
binary-validator = "0.13.2"
kotlinx-coroutines = "1.7.2"
androidx-lifecycle = "2.6.1"
androidx-fragment = "1.6.1"
appcompat = "1.6.1"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-fragment = { module = "androidx.fragment:fragment", version.ref = "androidx-fragment" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }

androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

test-junit4 = { module = "junit:junit", version = "4.13.2" }
test-turbine = { module = "app.cash.turbine:turbine", version = "0.12.3" }

[plugins]
gradle-android-application = { id = "com.android.application", version.ref = "android-plugin" }
gradle-android-library = { id = "com.android.library", version.ref = "android-plugin" }
gradle-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
gradle-binary-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binary-validator" }